Repository PEEC-Nature-Youth-Group/pumaguard, pull requests merged in 2024-10, with the labels that each got.

#91 Started working on a script for the notebook
  scripts/train.py
Labels: hacktoberfest-accepted

#96 Add no_proxy to devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: hacktoberfest-accepted

#95 Downgrade dependencies
  poetry.lock
  pyproject.toml
  tests/test_tensorflow.py
Labels: hacktoberfest-accepted

#97 Add angle 3 to data
  data/stable/angle 3/Lion/SYFW5835.JPG
  data/stable/angle 3/Lion/SYFW5836.JPG
  data/stable/angle 3/Lion/SYFW5837.JPG
  data/stable/angle 3/Lion/SYFW5843.JPG
  data/stable/angle 3/Lion/SYFW5844.JPG
  data/stable/angle 3/Lion/SYFW5845.JPG
  data/stable/angle 3/Lion/SYFW6557.JPG
  data/stable/angle 3/Lion/SYFW6558.JPG
  data/stable/angle 3/Lion/SYFW6559.JPG
  data/stable/angle 3/Lion/SYFW6594.JPG
  data/stable/angle 3/Lion/SYFW6595.JPG
  data/stable/angle 3/Lion/SYFW6596.JPG
  data/stable/angle 3/No Lion/SYFW0005.JPG
  data/stable/angle 3/No Lion/SYFW4164.JPG
  data/stable/angle 3/No Lion/SYFW4238.JPG
  data/stable/angle 3/No Lion/SYFW5666.JPG
  data/stable/angle 3/No Lion/SYFW5669.JPG
  data/stable/angle 3/No Lion/SYFW5779.JPG
  data/stable/angle 3/No Lion/SYFW5780.JPG
  data/stable/angle 3/No Lion/SYFW5781.JPG
  data/stable/angle 3/No Lion/SYFW5785.JPG
  data/stable/angle 3/No Lion/SYFW5792.JPG
  data/stable/angle 3/No Lion/SYFW5793.JPG
  data/stable/angle 3/No Lion/SYFW5795.JPG
  data/stable/angle 3/No Lion/SYFW5876.JPG
  data/stable/angle 3/No Lion/SYFW5877.JPG
  data/stable/angle 3/No Lion/SYFW5878.JPG
  data/stable/angle 3/No Lion/SYFW6330.JPG
  data/stable/angle 3/No Lion/SYFW6331.JPG
  data/stable/angle 3/No Lion/SYFW6333.JPG
  data/stable/angle 3/No Lion/SYFW6334.JPG
  data/stable/angle 3/No Lion/SYFW6430.JPG
  data/stable/angle 3/No Lion/SYFW6457.JPG
  data/stable/angle 3/No Lion/SYFW6458.JPG
  data/stable/angle 3/No Lion/SYFW6539.JPG
  data/stable/angle 3/No Lion/SYFW6540.JPG
  data/stable/angle 3/No Lion/SYFW6541.JPG
  data/stable/angle 3/No Lion/SYFW6550.JPG
  data/stable/angle 3/No Lion/SYFW6551.JPG
  data/stable/angle 3/No Lion/SYFW6553.JPG
  data/stable/angle 3/No Lion/SYFW6554.JPG
  data/stable/angle 3/No Lion/SYFW6561.JPG
  data/stable/angle 3/No Lion/SYFW6591.JPG
  data/stable/angle 3/No Lion/SYFW6593.JPG
Labels: hacktoberfest-accepted

#98 Fix data path in notebook
  notebooks/Mountain_Lions.ipynb
Labels: hacktoberfest-accepted

#99 Move work directory to temporary folder
  notebooks/Mountain_Lions.ipynb
Labels: hacktoberfest-accepted

#100 Downgrade snap base for Python 3.10
  snap/snapcraft.yaml
Labels: hacktoberfest-accepted

#101 Added 2nd cell of notebook to script
  scripts/train.py
Labels: hacktoberfest-accepted

#103 Added 3rd cell to the script
  scripts/train.py
Labels: hacktoberfest-accepted

#110 added 4th cell to script
  scripts/train.py
Labels: hacktoberfest-accepted

#114 Added page for camer locations project
  docs/source/About.rst
  docs/source/Cameralocation.rst
Labels: hacktoberfest-accepted

#117 The website says the trailcam is 12v so we would need around a 50w solar panel.
  docs/camerapowerconsumption.rst
Labels: hacktoberfest-accepted

#115 Created weatherproofing page
  docs/source/WeatherProofing.rst
Labels: hacktoberfest-accepted

#116 Lights
  docs/Lights
Labels: hacktoberfest-accepted

#118 To power Rasberry Pi, solar panels would be a useful option.
  docs/source/solarpanelresearch.rst
Labels: hacktoberfest-accepted

#83 Create Camera parts
  docs/source/Camera parts
Labels: hacktoberfest-accepted

#148 Fix indentation
  notebooks/Mountain_Lions.ipynb
Labels: software

#150 Properly generate module documentation
  Makefile
Labels: documentation

#152 Add proxy settings to devcontainer
  .devcontainer/devcontainer.json
Labels: software

#149 Add classify script
  pylintrc
  pyproject.toml
  scripts/classify.py
  scripts/launch-pi-zero.sh
Labels: software

#176 Add page with performance numbers
  docs/source/Performance.rst
  docs/source/index.rst
Labels: power
